####### BUILD CONTAINER #######
FROM elixir:1.7.2-alpine AS builder

MAINTAINER Dave Persing <persing@adobe.com>

WORKDIR /opt/app

ENV MIX_ENV=prod

RUN apk add --update git \
  && mix local.hex --force \
  && mix local.rebar --force

COPY . .

RUN mix do deps.get, deps.compile, compile

RUN \
  mkdir -p /opt/built && \
  mix release --env=prod --verbose && \
  cp _build/${MIX_ENV}/rel/bot_army/releases/0.1.0/bot_army.tar.gz /opt/built && \
  cd /opt/built && \
  tar -xzf bot_army.tar.gz && \
  rm bot_army.tar.gz

####### RUN CONTAINER #######
FROM alpine:3.8

RUN apk add --update openssl-dev bash

ENV REPLACE_OS_VARS=true \
    APP_NAME=bot_army

WORKDIR /opt/app

COPY --from=builder /opt/built .

CMD /opt/app/bin/bot_army foreground
